### ISSUE TITLE
调用方法 TestDOService::create(T record), 未手动设置is_deleted字段的值, 报错插入异常.

### ISSUE THREAD

**Issue by edwardzhaokl** [myoss-cloud/myoss-mybatis#2]
实体类TestDO继承审计父类AuditIdEntity, 
调用方法 TestDOService::create(T record), 未手动设置is_deleted字段的值, 报错插入异常.

InsertMapperTemplate::insert(TableInfo tableInfo, MappedStatement ms)方法中以下代码导致: 
`boolean fillInsert = (columnInfo.isPrimaryKey() && GenerationType.USE_GENERATED_KEYS != generationType)  || columnInfo.haveFillRule(FillRule.INSERT) || columnInfo.isLogicDelete();`

是不是可以考虑create的时候, is_deleted默认指定为'N'或者交由数据库填充默认值, 而无需手动set.

还是说从设计上来讲, 既然是审计字段, 就要谨慎的指定所有字段值.

感谢~

**Comment by myoss** [comment]
使用插件的方式处理默认值：

```
    @ConditionalOnMissingBean
    @Bean
    public ParameterHandlerCustomizer persistenceParameterHandler() {
        return new DefaultParameterHandlerCustomizer();
    }
```

**Comment by edwardzhaokl** [comment]
学习了, 感谢
